main: me.Chestsort.main.ChestSort
name: ChestSort
author: CJM
version: 1.1
api-version: 1.13
description: Sort Chests by Type
commands:
   ChestSort:
      aliases: [cs]
      usage: /<SortChest> [command]
      description: Main command